# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
name: CD NCP

## 실행 브랜치 - main브랜치에 push가 발생할 경우
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      ## Project JDK 17 Setting
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        ## Gradle 사용권한 셋팅
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      ## main 브랜치일경우 application.yml 파일 제작
      - name: make application.yml
        if: contains(github.ref, 'main')
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yml

      ## 프로젝트 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

      ## ssh접속 후 jar파일 옮기기
      - name: Delivery jar to remote ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: ${{ secrets.NCP_SERVER_PORT }}
          source: "build/libs/mybox-0.0.1-SNAPSHOT.jar"
          target: "./source/"
          rm: true

      ## ssh 배포 스크립트 실행
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: ${{ secrets.NCP_SERVER_PORT }}
          script: |
            cd ./source/build/libs/
            bash nohup java -jar -Dspring.profiles.active=prod mybox-0.0.1-SNAPSHOT.jar 1> log.txt 2>&1 &

